### ISSUE TITLE
[publish] Validate data package prior to trying to publish

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpm-py#15]
- [x] Test
- [x] Validate
- [x] Report JSON errors (very common) usefully
- [ ] Report validation errors usefully and concisely

**Comment by rgrp** [comment]
Output from validation error from underlying library is very verbose if you just print to console.

**Comment by roll** [comment]
In goodtables I use first line from every error https://github.com/frictionlessdata/goodtables-py/blob/next/goodtables/profiles/datapackage.py#L19

**Comment by Fak3** [comment]
Related: https://github.com/frictionlessdata/datapackage-py/issues/113

**Comment by Fak3** [comment]
When the 'path' is missing for a resource, the first line of error is quite cryptic:
```
{'schema': {'fields': [{'title': '', 'type': 'date', 'format': 'default', 'name': 'Date', 'description': ''}, {'title': '', 'type': 'number', 'format': 'default', 'name': 'Price', 'description': ''}]}} is not valid under any of the given schemas
```
I wonder if we can or should make it more enlightening.

**Comment by roll** [comment]
@Fak3 
Would you like to make a PR to `datapackage-py`. I suppose validation logic is here - https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/schema.py (cc @vitorbaptista )

**Comment by Fak3** [comment]
JSON validation error messages was fixed upstream:
```
(dpmpy) u1@linux-1zpk:/home/z/pproj/gas_price_data> dpmpy validate
ERROR Unable to parse JSON at "/home/z/pproj/gas_price_data/datapackage.json". Expecting property name: line 2 column 1 (char 2)
```

**Comment by Fak3** [comment]
This task can be considered done. Clarifying validation errors moved to #65.
