### ISSUE TITLE
Handle presigned url upload errors

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#28]
Some possible cases would be:
* presigned url expired
* permission denied

**Comment by Fak3** [comment]
If the server has AWS_REGION='us-west2' and the bucket was created in the 'US Standard' region, then the creation of s3 presigned url succeeds, dpmpy silently succeeds putting data to this url, but the new file never shows up in the bucket. We should check if there is any error code returened for the PUT request.

**Comment by rgrp** [comment]
@Fak3 is this not a server misconfiguration issue. I get that the silent fail is painful but wonder if we should really have the test for this in the server.

**Comment by Fak3** [comment]
By test you mean startup check that bucket region matches the AWS_REGION from environment? Or the unittest?

**Comment by rgrp** [comment]
@Fak3 i am saying *here* that I do not think a test is needed or handling in the command line (though I could be wrong).

Whatever the server needs to do to avoid this we should highlight in the server issue tracker.

**Comment by rufuspollock** [comment]
WONTFIX as per discussion above - this looks to be a server issue IMO.
