### ISSUE TITLE
Rename to dpm-py to match other tooling?

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/dpm-py#3]

**Comment by roll** [comment]
And `dpm -> dpm-js` I suppose.

**Comment by rgrp** [comment]
@roll we can do but usually the repo will match the command line tool name ... (?)

**Comment by rgrp** [comment]
@roll @danfowler I think you are right that the repo can be named this way even if the tool is dpmpy on the command line. wdyt?

**Comment by roll** [comment]
I agree

**Comment by danfowler** [comment]
@rgrp yes

**Comment by roll** [comment]
@rgrp 
It seems done. So what about `dpm` -> `dpm-js` for consistency?

**Comment by rgrp** [comment]
FIXED.

Re dpm -> dpm-js - i agree.
