### ISSUE TITLE
Add `delete` command

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#38]
Should use dpr api to perform soft-delete of the datapackage

_see also: add purge command #39_

**Comment by rgrp** [comment]
@Fak3 could you spec out the exact signature of the command e.g. does it allow an argument e.g.

```
dpmpy delete mypublisher/cool-package

dpmpy delete {package-identifier}
```

What does it do if no argument provided (check we are in a data package directory and use that).

**Comment by Fak3** [comment]
I thought that for now it should only perform deletion of datapackage in current dir, like the `publish` command does. To allow any action on arbitrary datapackage, we should agree on how the user would specify datapackage identifier - `publisher/packagename` or `@publisher/packagename` or maybe even `publisher packagename1 packagename2 packagename3`? Will we ever need a wildcards to perform action? Like `dpmpy delete publisher/*`
