### ISSUE TITLE
Organize configuration options and defaults in the code better

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#44]
Current issues include:
- [ ] [`DEFAULT_SERVER` config](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/constants.py#L12) with no way to override it? 
- [ ] passing the config and arguments to subcommands looks ugly and non-DRY
   - [ ] config fallbacks are spread in codebase. [Example of config conditionals outside of config](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/main.py#L42)

**Comment by Fak3** [comment]
Copying comment from #43:

Some problems and proposed solutions:
* To handle the configuration and auth I would suggest to make the client lib\API class-based, where the `DpmClient` instance is to be created and configured at the start by the lib user (as dmpmy cli)
* Passing the config and defaults to subcommands would be replaced by passing the instance of the client, kepping it responsible of config in one place. (to address #44)  
* Divorcing client lib from click would mean introduction of logging the messagess for the lib users(as dmpmy cli) to handle in a way they need.
I would suggest to use the structlog (it is flexible and blessed by the community) 
   * To still have the neat click progessbars, the dmpmy cli can override `on_file_upload()` method of the api client (by subclassing it)

**Comment by rgrp** [comment]
DUPLICATE / MERGE with #43
