### ISSUE TITLE
[doc] Add docs on authentication

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#45]
We use username\password\jwt, that worth to be documented in more details.

Push the docs at https://github.com/frictionlessdata/dpr-docs

Learn the mkdocs and create basic docs layout. See example at https://github.com/openspending/docs

**Comment by rufuspollock** [comment]
DUPLICATE of https://github.com/frictionlessdata/dpr-api/issues/162

**Comment by Fak3** [comment]
https://github.com/frictionlessdata/dpr-docs/pull/7
