### ISSUE TITLE
Data validation on the client

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#46]
Dpm should validate the data before sending it to the server. It could be possibly done with goodtables or jsontableschema.Table
```
$ dpmpy datavalidate [file-path]
```
* [file-path] - run this against a given file. Look in the resources to see if this file is there and if so use the schema. Otherwise just do goodtables table … 
  * If no file provided run validate against each resource in turn in the datapackage
* Output to stdout.
  * Default:  human-readable - nice version of output from goodtables.
  * Option for JSON e.g. --json to put machine readable output
* check goodtables command line tool and follow if possible. Can probably reuse code 
* Auto-run this before publish unless explicit suppression (e.g. --skip-datavalidate)
* Use goodtables

### Analysis
We can use goodtables:
```
import goodtables
# check an individual CSV file
report1 = goodtables.Inspector().inspect('data/valid.csv', schema={'fields': [{'name': 'field1'}]})

```

### Original user stories 
_As a Publisher [owner/member] I want to validate the data I am about to publish to the registry so that I publish “good” data and know that I am doing so and do not have to manually check that the published data looks ok (e.g. rendering charts properly) (and if wrong I have to re-upload)_

---
Extracted from OKI review issue and comment: https://github.com/frictionlessdata/dpm-py/issues/41#issuecomment-265200760

**Comment by rgrp** [comment]
Useful to do but not on critical path right now or MVP. Pushing to backlog.

**Comment by Fak3** [comment]
accidentally closed in boards. reopen
