### ISSUE TITLE
Implement `dpmpy tag`

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#69]
Should send the server request to tag a datapackage in the current dir.

* add test

### Original user stories
_As a {Publisher} I want to tag datapackage to create a snapshot of data on the registry server, so that consumers can refer to it_
_As a {Publisher} I want to be warned that a tag exists, when I try to overwrite it, so that I don’t accidentally overwrite stable tagged data, which is relied on by consumers._
_As a {Publisher} I want to be able to overwrite the previously tagged datapackage, so that I can fix it if I mess up._

**Comment by rufuspollock** [comment]
FIXED. This is working!
