### ISSUE TITLE
Make publish online git repo script optional

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpm-py#86]
Currently in https://github.com/frictionlessdata/dpm-py/blob/master/dpm/bin/import_git.py and dependencies are in setup.py.

Move this to be an optional extra script in `/examples/` directory (put README.md in examples directory with details of the requirements).

Why: this is not core functionality and it adds an extra unnecessary dependency. It's useful so we should keep around and put in `/examples/`

**Comment by subhankarb** [comment]
FIXED
